### PR TITLE
Update clsAPINFO.vb

### PR DESCRIPTION
**Pull request by adultmm**
FIX: EMM doesn't set the scraped language, this fix solves it

### CODE REVIEW

**Comment by DanCooper** [comment]
Wrong way. The language has to be set via source settings, changed by contextmenu or NFO. A scraper never provides a language setting for a movie, a scraper always use the language (if possible) that a movie is set to.

**Comment by krisz-gemini** [comment]
Please help me, to understand it. 

We set the language of the source to German, but some movies don't have German info on TMDB. Without this change, every nfo contains "de-DE" as language, but it's wrong. It'd be better to set this language as the language of the title and the plot. 

What do you think?

**Comment by adultmm** [comment]
Please help me, to understand it.

We set the language of the source to German, but some movies don't have German info on TMDB. Without this change, every nfo contains "de-DE" as language, but it's wrong. It'd be better to set this language as the language of the title and the plot.

What do you think?

**Comment by DanCooper** [comment]
At the beginning, the language had to be set individually for each data, image and trailer scraper. If you wanted to have a single film or series scrapped in a different language, you always have to change the basic settings and then reset them again.

With the current solution, the language is set per source and can be adapted for individual films / series if necessary. The language setting defines the text and image language that the user want for an entry and the scraper has to use, not the language that perhaps has been used because of a fallback inside a scraper. If the language whould be changed by scraper it no longer whould be possible to later rescrape to get the title, plot, whatever in that language you want.

So yes, most of all entries in the NFO will be e.g. "de_DE". I use this feature to set movies and tv shows to "en_GB" that are english audio stream only or not even released in my native language to get the data and images in english.

**Comment by DanCooper** [comment]
... also you should start to push my latest changes to you fork because I've changed a lot for multi-rating, unique ids and other features and i think you have to change some points in your scraper(s). I'm not yet finished will all the changes but most of the API changes are done. Otherwise xou addons will no longer work with the next release.

**Comment by adultmm** [comment]
Thanks for the information. I sent your answer to my users. They miss the "language of the scraped data" field, but in this case I can't help them.

I'll merge your changes, of course. Thanks again

**Pull request closed without merging**
