### PR TITLE
sync with DanCooper master trunk.

### PR DESCRIPTION
**Pull request by msavazzi**
as usual some conflicts to be fixed.

### CODE REVIEW

**Comment by msavazzi** [comment]
merge without issues. No impact on your code.

**Comment by msavazzi** [comment]
please merge this in as now VLC.DotNet is created runtime correctly.
I need help to test the trailer functionality (never used it before)

**Comment by DanCooper** [comment]
Some questions:
- why you have changed to build path to EmberMM? This brings no advantage over the solution that we use now already for ages. I'm working with many external script to copy/move settings for debugging and testing, also the build batch file does no longer work. I do not want to have to change all my scripts. Please change the paths back to its previous settings.
- why the whole source code of VLC libs are in our project? All libs are available in NuGet and this is the only way to update them easy if needed.

**Comment by msavazzi** [comment]
1) it was doing a mess with the libraries. I can update the scripts for you if you want.
It should be a simple find replace from EmberMm - {build} - {platform} to EmberMm/build} - {platform}
I discovered projects building in weird dies... Now is all normalized

2) because nuget files are corrupted and give error. The code should not be included but linked to the original repository.

It now compiles in x86, x64, AnyCpu

Sent from my mobile, excuse for typo and brevity. Inviato dal cellulare, scusate per brevità e errori.
________________________________
Da: DanCooper<mailto:notifications@github.com>
Inviato: ‎15/‎02/‎2016 15:14
A: DanCooper/Ember-MM-Newscraper<mailto:Ember-MM-Newscraper@noreply.github.com>
Cc: Massimo Savazzi<mailto:massimo@savazzi.eu>
Oggetto: Re: [Ember-MM-Newscraper] sync with DanCooper master trunk. (#182)


Some questions:

  *   why you have changed to build path to EmberMM? This brings no advantage over the solution that we use now already for ages. I'm working with many external script to copy/move settings for debugging and testing, also the build batch file does no longer work. I do not want to have to change all my scripts. Please change the paths back to its previous settings.
  *   why the whole source code of VLC libs are in our project? All libs are available in NuGet and this is the only way to update them easy if needed.

**Comment by msavazzi** [comment]
Old paths restored.
Dan I would suggest you add your scripts in a folder (as I did for the sync.bat) so that if we have to change paths or similar we can fix the scripts too :)

**Comment by msavazzi** [comment]
Dan with regards to the VLC.net project this is what I've done:
https://help.github.com/articles/about-git-subtree-merges/

Is the correct way to import a sub project...

**Comment by msavazzi** [comment]
playback works!

**Comment by war59312** [comment]
Forgotten?

🎱

**Comment by DanCooper** [comment]
Nope, to many things that are not correct, wrong or not allowed.

**Pull request closed without merging**
