### PR TITLE
updating to add VLC.DotNet

### PR DESCRIPTION
**Pull request by msavazzi**

### CODE REVIEW

**Comment by msavazzi** [comment]
Dan, please merge it...

**Comment by Cocotus** [comment]
I believe Dan merged it by hand, as stated in comment here: https://github.com/DanCooper/Ember-MM-Newscraper/pull/179

Going to check it out now :+1:

**Comment by msavazzi** [comment]
It reports me is not merged :|

Sent from my mobile, excuse for typo and brevity. Inviato dal cellulare, scusate per brevità e errori.
________________________________
Da: Cocotus<mailto:notifications@github.com>
Inviato: ‎04/‎02/‎2016 21:01
A: DanCooper/Ember-MM-Newscraper<mailto:Ember-MM-Newscraper@noreply.github.com>
Cc: Massimo Savazzi<mailto:massimo@savazzi.eu>
Oggetto: Re: [Ember-MM-Newscraper] updating to add VLC.DotNet (#181)


I believe Dan merged it by hand, as stated in comment here: #179<https://github.com/DanCooper/Ember-MM-Newscraper/pull/179>

Going to check it out now [:+1:]

**Comment by msavazzi** [comment]
Dan please merge this as I need it to be in to finish VLC

**Pull request merged**
