### PR TITLE
updated all nuget packages. added vlc.dotnet. removed axVLC. Removed …

### PR DESCRIPTION
**Pull request by msavazzi**
…x64 compile option as vlc.dotnet appear to crash in x64 mode

### CODE REVIEW

**Comment by msavazzi** [comment]
Merge update for VLC

**Comment by Cocotus** [comment]
Thanks for this - axVlc often made problems in the past :+1:

**Comment by msavazzi** [comment]
checking Trailer dialog as it does not invoke player

**Comment by DanCooper** [comment]
manually merged in https://github.com/DanCooper/Ember-MM-Newscraper/commit/ed2067b61caf35984095b8b237bceb040a0e6b26

**Pull request closed without merging**
